try1

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -8,36 +8,50 @@ on:
 
 jobs:
   build_and_test:
-    name: Build and Test
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
+
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
           java-version: '11'
           distribution: 'temurin'
+
       - name: Setting Permissions
         run: chmod a+x gradlew
+
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
+        uses: gradle/gradle-build-action@...
         with:
           arguments: build
+
       - name: Test with Gradle
-        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
+        uses: gradle/gradle-build-action@...
         with:
           arguments: test
+
       - name: Run Test Coverage
         run: ./gradlew jacocoTestReport
+
       - name: Jacoco
-        uses: cicirello/jacoco-badge-generator@v2.9.0
+        uses: cicirello/jacoco-badge-generator@v2.11.0
         with:
           jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
+
           generate-summary: true
           summary-filename: coverage1.json
+          badges-directory: '.'
+
           fail-on-coverage-decrease: true
           fail-on-branches-decrease: true
+
+      - name: Check coverage file
+        run: |
+          echo ">>> PWD: $(pwd)"
+          ls -l coverage1.json || echo "coverage1.json not found"
+          cat coverage1.json || echo "cannot cat coverage1.json"
+
       - name: Commit coverage
         uses: EndBug/add-and-commit@v7
         with:
@@ -45,20 +59,4 @@ jobs:
           default_author: github_actions
           message: 'update coverage summary'
           push: true
-
-  build_and_publish_docker_image:
-    name: Publish to Docker Hub
-    runs-on: ubuntu-latest
-    needs: [build_and_test]
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Build Docker image
-        run: docker build -f ./Dockerfile -t ${{ secrets.DOCKER_REPO }} .
-      - name: Push Docker image
-        run: docker push ${{ secrets.DOCKER_REPO }}
+          skip_empty_commit: true
